### ISSUE TITLE
`topn()` fails on large number of `NULL`s

### ISSUE THREAD

**Issue by SimonMTS** [timescale/timescaledb-toolkit#767]
**Relevant system information:**
 - OS: 6.1.41-1-MANJARO
 - PostgreSQL version: 15.4
 - TimescaleDB Toolkit version: 1.17.0
 - Installation method: docker (also happens on Timescale Cloud)

**Describe the bug**
Using `topn()` on a large number of `NULL` rows causes an `Option::unwrap()` error.
On a smaller number of rows it works as expected.

**To Reproduce**
1. Start the image `timescale/timescaledb-ha:pg15-all`.
   (This is how I reproduced it, but it probably happens on all recent versions)
2. Run the following SQL to setup the database:
   ```
   CREATE TABLE public.example (time TIMESTAMPTZ NOT NULL, string_value TEXT NULL);

   INSERT INTO public.example (time, string_value)
       SELECT time, NULL AS string_value
       FROM generate_series(now() - interval '5 day', now(), interval '1 second') AS g1(time);
   ```
3. Run the following query to trigger the bug:
   `SELECT topn(mcv_agg(1, string_value)) FROM public.example;`
4. See the error `ERROR: called 'Option::unwrap()' on a 'None' value`

**Expected behavior**
On smaller (`NULL`) datasets `topn()` results in:
```
 topn
------
(0 rows)
```
I expect this behaviour not to change depending on dataset size.

**Actual behavior**
On larger (`NULL`) datasets `topn()` results in:
```
ERROR:  called `Option::unwrap()` on a `None` value
```

**Additional context**
The bug can be reproduced on Timescale Cloud and locally in docker.

This bug was particularly pernicious because it only occurs on larger datasets.
So we didn't encounter it during testing.

**Workaround**
A Timescale Support agent quickly provided us with a workaround.
Replacing `string_value` with `COALESCE(string_value,''::text))`,
e.g. `SELECT topn(mcv_agg(1, COALESCE(string_value,''::text))) FROM public.example;`

Which changes the behaviour to return an empty string instead of no results.
But did solve our production issue.

**Comment by supergoudvis116** [comment]
Cool story bro, no one seem to care.

**Comment by vanderhoop** [comment]
FWIW, I don't think this is always related to the presence of `NULL` values. We're encountering the same error—`called 
'Option::unwrap()' on a 'None' value`—when aggregating with `mcv_agg` on a non-null column. The aggregation seems to work fine on small datasets but chokes when we expand the time window.

We've tried the `COALESCE` trick mentioned in the summary, and no dice.

Given the issue appears similar, I would suggest changing the title of this issue to drop the reference to NULLs. Else, I can create a new issue.

**Comment by vanderhoop** [comment]
> Okay, so we found a workaround for our case. 
> ...
> By supplying an upper bound of time_column <= now(), the issue disappeared.

Okay, so more information here 😄 

The lower bound is also important here. Our users can select from preset time windows, and if they select a window whose lower bound is far beyond the first record for a given query, the `mcv_agg` call blows up with the `'Option::unwrap()' on a 'None' value` error.

So based on our (minimal) experiments, it seems that the creation of the `mcv_agg` breaks unless the bounds are scoped to where there is sure to be data. We can work around that for now, but I think it would make sense to make mcv_agg more resilient long term.

**Comment by supergoudvis116** [comment]
So @vanderhoop did a decent research @SimonMTS took the time to create a ticket we have hosted instances that have this issue and you all can't even reply. Great!

**Comment by Dvdandrades** [comment]
- PostgreSQL version: 18.4
- TimescaleDB Toolkit version: 1.25.0

This query now gives:
```sql
CREATE TABLE public.example (time TIMESTAMPTZ NOT NULL, string_value TEXT NULL);

INSERT INTO public.example (time, string_value)
    SELECT time, NULL AS string_value
    FROM generate_series(now() - interval '5 day', now(), interval '1 second') AS g1(time);

SELECT topn(mcv_agg(1, string_value)) FROM public.example;
```

```text
 topn
------
(0 rows)
```

I think the bug has been resolved @surister , as it now properly handles empty and `NULL` states.

It handle `NULL` values via:
https://github.com/timescale/timescaledb-toolkit/blob/ddcba39c2136db971a43eaffb204795c5896b067/extension/src/frequency.rs#L931-L944

**Comment by surister** [comment]
timescaledb_toolkit: 1.23.0

The issue still exists (in 1.23.0), I could reproduce it with `...interval '30 day', now()...`

**Comment by surister** [comment]
In `1.24.0` it's fixed, it was accidentally fixed in 3ab6182258bb8d2f76baeebbb8857fdeb9951bf9 with `state.map(|state| crate::do_serialize!(state))`.

**Comment by Dvdandrades** [comment]
Ah, I remember now. I did that and forgot about it. I was trying to fix a lot of `Option::unwrap() on a None value` errors and completely forgot I’d already solved it in `frequency` for another issue.

**Comment by vanderhoop** [comment]
> In 1.24.0 it's fixed, it was accidentally fixed in https://github.com/timescale/timescaledb-toolkit/commit/3ab6182258bb8d2f76baeebbb8857fdeb9951bf9 with state.map(|state| crate::do_serialize!(state)).

@surister @Dvdandrades Makes sense to add a regression test here before closing

**Comment by surister** [comment]
Let's celebrate https://github.com/timescale/timescaledb-toolkit/issues/767 for the last time.

<img width="1600" height="900" alt="Image" src="https://github.com/user-attachments/assets/142a1d47-ff1e-4f25-83ef-ec06f6406a63" />

**Comment by SimonMTS** [comment]
> Let's celebrate [#767](https://github.com/timescale/timescaledb-toolkit/issues/767) for the last time.

That's lovely xd, so long and farewell [#767](https://github.com/timescale/timescaledb-toolkit/issues/767).
(And thanks for the fix as well.)
