### ISSUE TITLE
Package timescaledb-toolkit-postgresql-16 is not available (packagecloud still shows it)

### ISSUE THREAD

**Issue by tonyalaribe** [timescale/timescaledb-toolkit#799]
**Relevant system information:**
 - OS:  Ubuntu 24.04
 - PostgreSQL version 16.2
 - TimescaleDB Toolkit version 1.18
 - Installation method: ubuntu server

**Describe the bug**

sudo apt-get install timescaledb-toolkit-postgresql-16=1:1.18.0~ubuntu22.04
which is recommended on package cloud does not work: https://packagecloud.io/timescale/timescaledb/packages/ubuntu/jammy/timescaledb-toolkit-postgresql-16_1.18.0~ubuntu22.04_arm64.deb?distro_version_id=237 

Seems the file used to exist but no longer exists.

<img width="664" alt="CleanShot 2024-05-12 at 02 28 15@2x" src="https://github.com/timescale/timescaledb-toolkit/assets/6564482/e2567dca-ea63-461b-8f1f-bd3f48f89696">

**Comment by ignatiusreza** [comment]
Until distribution for noble is fixed, would it be recommended to use the one for jammy in Ubuntu 24.04?

**Comment by hugo-lovighi** [comment]
Any news about this issue ?

**Comment by tonyalaribe** [comment]
I eventually compiled it from source. Not sure this is this has been fixed.

**Comment by Sh1ken** [comment]
Same problem still persist for `timescaledb-toolkit-postgresql-16` on 24.04

**Comment by dn0** [comment]
Isn't this problem affecting only arm64/aarch64? The platform looks to be supported but deb packages are not provided.

**Comment by mohag** [comment]
> Isn't this problem affecting only arm64/aarch64? The platform looks to be supported but deb packages are not provided.

When I checked, it was missing on amd64 (at time of my comment)

**Comment by ghostcipher1** [comment]
Facing same issue on self-hosted running PostgreSQL 16 and unable to install. I'm running Ubuntu 22.04.

**Comment by jbx1** [comment]
Same problem with timescaledb-toolkit-postgresql-17 on Ubuntu 24.04 LTS.

**Comment by feikesteenbergen** [comment]
Toolkit now has packages (as of 1.21.0) for Ubuntu 24.04 for PostgreSQL 15, 16 and 17.

**Comment by svenklemm** [comment]
We usually align this with the range of major postgres versions supported by timescaledb which atm is 15-18
